
export const INDICATOR_LIST = [

    { code: 'gini', name: 'Inidice Gini' },
    { code: 'tugurios', name: 'Poblacion viviendo en barrios de tugurios'},
    { code: 'brecha3', name: 'Brecha de Pobreza 3 USD al dia' },
    { code: 'brecha420', name: 'Brecha de Pobreza 4.20 USD al dia' },
    { code: 'consumomedio', name: 'Consumo medio o ingresos per capita segn encuestas' },
];

export const COUNTRY_LIST = [
        
    { code: 'ABW',	 name: 'Aruba' },
    { code: 'AFG',	 name: 'Afganistán' },
    { code: 'AGO',	 name: 'Angola' },
    { code: 'ALB',	 name: 'Albania' },
    { code: 'AND',	 name: 'Andorra' },
    { code: 'ARE',	 name: 'Emiratos Árabes Unidos' },
    { code: 'ARG',	 name: 'Argentina' },
    { code: 'ARM',	 name: 'Armenia' },
    { code: 'ASM',	 name: 'Samoa Americana' },
    { code: 'ATG',	 name: 'Antigua y Barbuda' },
    { code: 'AUS',	 name: 'Australia' },
    { code: 'AUT',	 name: 'Austria' },
    { code: 'AZE',	 name: 'Azerbaiyán' },
    { code: 'BDI',	 name: 'Burundi' },
    { code: 'BEL',	 name: 'Bélgica' },
    { code: 'BEN',	 name: 'Benin' },
    { code: 'BFA',	 name: 'Burkina Faso' },
    { code: 'BGD',	 name: 'Bangladesh' },
    { code: 'BGR',	 name: 'Bulgaria' },
    { code: 'BHR',	 name: 'Bahrein' },
    { code: 'BHS',	 name: 'Bahamas' },
    { code: 'BIH',	 name: 'Bosnia y Herzegovina' },
    { code: 'BLR',	 name: 'Belarús' },
    { code: 'BLZ',	 name: 'Belice' },
    { code: 'BMU',	 name: 'Bermudas' },
    { code: 'BOL',	 name: 'Bolivia' },
    { code: 'BRA',	 name: 'Brasil' },
    { code: 'BRB',	 name: 'Barbados' },
    { code: 'BRN',	 name: 'Brunei Darussalam' },
    { code: 'BTN',	 name: 'Bhután' },
    { code: 'BWA',	 name: 'Botswana' },
    { code: 'CAF',	 name: 'República Centroafricana' },
    { code: 'CAN',	 name: 'Canadá' },
    { code: 'CEB',	 name: 'Europa Central y del Báltico' },
    { code: 'CHE',	 name: 'Suiza' },
    { code: 'CHI',	 name: 'Islas del Canal' },
    { code: 'CHL',	 name: 'Chile' },
    { code: 'CHN',	 name: 'China' },
    { code: 'CIV',	 name: 'Côte dIvoire' },
    { code: 'CMR',	 name: 'Camerún' },
    { code: 'COD',	 name: 'Congo, República Democrática del' },
    { code: 'COL',	 name: 'Colombia' },
    { code: 'COM',	 name: 'Comoras' },
    { code: 'CPV',	 name: 'Cabo Verde' },
    { code: 'CRI',	 name: 'Costa Rica' },
    { code: 'CUB',	 name: 'Cuba' },
    { code: 'CUW',	 name: 'Curacao' },
    { code: 'CYM',	 name: 'Islas Caimán' },
    { code: 'CYP',	 name: 'Chipre' },
    { code: 'CZE',	 name: 'República Checa' },
    { code: 'DEU',	 name: 'Alemania' },
    { code: 'DJI',	 name: 'Djibouti' },
    { code: 'DMA',	 name: 'Dominica' },
    { code: 'DNK',	 name: 'Dinamarca' },
    { code: 'DOM',	 name: 'República Dominicana' },
    { code: 'DZA',	 name: 'Argelia' },
    { code: 'ECU',	 name: 'Ecuador' },
    { code: 'EGY',	 name: 'Egipto, República Árabe de' },
    { code: 'ERI',	 name: 'Eritrea' },
    { code: 'ESP',	 name: 'España' },
    { code: 'EST',	 name: 'Estonia' },
    { code: 'ETH',	 name: 'Etiopía' },
    { code: 'EUU',	 name: 'Unión Europea' },
    { code: 'FIN',	 name: 'Finlandia' },
    { code: 'FJI',	 name: 'Fiji' },
    { code: 'FRA',	 name: 'Francia' },
    { code: 'FRO',	 name: 'Islas Feroe' },
    { code: 'FSM',	 name: 'Micronesia (Estados Federados de)' },
    { code: 'GAB',	 name: 'Gabón' },
    { code: 'GBR',	 name: 'Reino Unido' },
    { code: 'GEO',	 name: 'Georgia' },
    { code: 'GHA',	 name: 'Ghana' },
    { code: 'GIB',	 name: 'Gibraltar' },
    { code: 'GIN',	 name: 'Guinea' },
    { code: 'GMB',	 name: 'Gambia' },
    { code: 'GNB',	 name: 'Guinea-Bissau' },
    { code: 'GNQ',	 name: 'Guinea Ecuatorial' },
    { code: 'GRC',	 name: 'Grecia' },
    { code: 'GRD',	 name: 'Granada' },
    { code: 'GRL',	 name: 'Groenlandia' },
    { code: 'GTM',	 name: 'Guatemala' },
    { code: 'GUM',	 name: 'Guam' },
    { code: 'GUY',	 name: 'Guyana' },
    { code: 'HIC',	 name: 'Ingreso alto' },
    { code: 'HND',	 name: 'Honduras' },
    { code: 'HRV',	 name: 'Croacia' },
    { code: 'HTI',	 name: 'Haití' },
    { code: 'HUN',	 name: 'Hungría' },
    { code: 'IDN',	 name: 'Indonesia' },
    { code: 'IMN',	 name: 'Isla de Man' },
    { code: 'IND',	 name: 'India' },
    { code: 'IRL',	 name: 'Irlanda' },
    { code: 'IRN',	 name: 'Irán, República Islámica del' },
    { code: 'IRQ',	 name: 'Iraq' },
    { code: 'ISL',	 name: 'Islandia' },
    { code: 'ISR',	 name: 'Israel' },
    { code: 'ITA',	 name: 'Italia' },
    { code: 'JAM',	 name: 'Jamaica' },
    { code: 'JOR',	 name: 'Jordania' },
    { code: 'JPN',	 name: 'Japón' },
    { code: 'KAZ',	 name: 'Kazajstán' },
    { code: 'KEN',	 name: 'Kenya' },
    { code: 'KGZ',	 name: 'Kirguistán' },
    { code: 'KHM',	 name: 'Camboya' },
    { code: 'KIR',	 name: 'Kiribati' },
    { code: 'KNA',	 name: 'Saint Kitts y Nevis' },
    { code: 'KOR',	 name: 'Corea, República de' },
    { code: 'KWT',	 name: 'Kuwait' },
    { code: 'LAO',	 name: 'República Democrática Popular Lao' },
    { code: 'LBN',	 name: 'Líbano' },
    { code: 'LBR',	 name: 'Liberia' },
    { code: 'LBY',	 name: 'Libia' },
    { code: 'LCA',	 name: 'Santa Lucía' },
    { code: 'LCN',	 name: 'América Latina y el Caribe' },
    { code: 'LIE',	 name: 'Liechtenstein' },
    { code: 'LKA',	 name: 'Sri Lanka' },
    { code: 'LSO',	 name: 'Lesotho' },
    { code: 'LTU',	 name: 'Lituania' },
    { code: 'LUX',	 name: 'Luxemburgo' },
    { code: 'LVA',	 name: 'Letonia' },
    { code: 'MAR',	 name: 'Marruecos' },
    { code: 'MCO',	 name: 'Mónaco' },
    { code: 'MDA',	 name: 'República de Moldova' },
    { code: 'MDG',	 name: 'Madagascar' },
    { code: 'MDV',	 name: 'Maldivas' },
    { code: 'MEX',	 name: 'Mexico' },
    { code: 'MHL',	 name: 'Islas Marshall' },
    { code: 'MKD',	 name: 'Macedonia del Norte' },
    { code: 'MLI',	 name: 'Malí' },
    { code: 'MLT',	 name: 'Malta' },
    { code: 'MMR',	 name: 'Myanmar' },
    { code: 'MNE',	 name: 'Montenegro' },
    { code: 'MNG',	 name: 'Mongolia' },
    { code: 'MNP',	 name: 'Mariana' },
    { code: 'MOZ',	 name: 'Mozambique' },
    { code: 'MRT',	 name: 'Mauritania' },
    { code: 'MUS',	 name: 'Mauricio' },
    { code: 'MWI',	 name: 'Malawi' },
    { code: 'MYS',	 name: 'Malasia' },
    { code: 'NAC',	 name: 'América del Norte' },
    { code: 'NAM',	 name: 'Namibia' },
    { code: 'NCL',	 name: 'Nueva Caledonia' },
    { code: 'NER',	 name: 'Níger' },
    { code: 'NGA',	 name: 'Nigeria' },
    { code: 'NIC',	 name: 'Nicaragua' },
    { code: 'NLD',	 name: 'Países Bajos' },
    { code: 'NOR',	 name: 'Noruega' },
    { code: 'NPL',	 name: 'Nepal' },
    { code: 'NRU',	 name: 'Nauru' },
    { code: 'NZL',	 name: 'Nueva Zelandia' },
    { code: 'OED',	 name: 'Miembros OCDE' },
    { code: 'OMN',	 name: 'Omán' },
    { code: 'PAK',	 name: 'Pakistán' },
    { code: 'PAN',	 name: 'Panamá' },
    { code: 'PER',	 name: 'Perú' },
    { code: 'PHL',	 name: 'Filipinas' },
    { code: 'PLW',	 name: 'Palau' },
    { code: 'PNG',	 name: 'Papua Nueva Guinea' },
    { code: 'POL',	 name: 'Polonia' },
    { code: 'PRI',	 name: 'Puerto Rico (US)' },
    { code: 'PRK',	 name: 'Corea, República Popular Democrática de' },
    { code: 'PRT',	 name: 'Portugal' },
    { code: 'PRY',	 name: 'Paraguay' },
    { code: 'PYF',	 name: 'Polinesia Francesa' },
    { code: 'QAT',	 name: 'Qatar' },
    { code: 'ROU',	 name: 'Rumania' },
    { code: 'RUS',	 name: 'Federación de Rusia' },
    { code: 'RWA',	 name: 'Rwanda' },
    { code: 'SAU',	 name: 'Arabia Saudita' },
    { code: 'SDN',	 name: 'Sudán' },
    { code: 'SEN',	 name: 'Senegal' },
    { code: 'SGP',	 name: 'Singapur' },
    { code: 'SLB',	 name: 'Islas Salomón' },
    { code: 'SLE',	 name: 'Sierra Leona' },
    { code: 'SLV',	 name: 'El Salvador' },
    { code: 'SMR',	 name: 'San Marino' },
    { code: 'SRB',	 name: 'Serbia' },
    { code: 'SSD',	 name: 'Sudán del Sur' },
    { code: 'SSF',	 name: 'África al sur del Sahara' },
    { code: 'STP',	 name: 'Santo Tomé y Príncipe' },
    { code: 'SUR',	 name: 'Suriname' },
    { code: 'SVK',	 name: 'República Eslovaca' },
    { code: 'SVN',	 name: 'Eslovenia' },
    { code: 'SWE',	 name: 'Suecia' },
    { code: 'SYR',	 name: 'República Árabe Siria' },
    { code: 'TCA',	 name: 'Islas Turcas y Caicos' },
    { code: 'TCD',	 name: 'Chad' },
    { code: 'TGO',	 name: 'Togo' },
    { code: 'THA',	 name: 'Tailandia' },
    { code: 'TJK',	 name: 'Tayikistán' },
    { code: 'TKM',	 name: 'Turkmenistán' },
    { code: 'TON',	 name: 'Tonga' },
    { code: 'TTO',	 name: 'Trinidad y Tobago' },
    { code: 'TUN',	 name: 'Túnez' },
    { code: 'TUR',	 name: 'Turquía' },
    { code: 'TUV',	 name: 'Tuvalu' },
    { code: 'TZA',	 name: 'Tanzanía' },
    { code: 'UGA',	 name: 'Uganda' },
    { code: 'UKR',	 name: 'Ucrania' },
    { code: 'URY',	 name: 'Uruguay' },
    { code: 'USA',	 name: 'Estados Unidos' },
    { code: 'UZB',	 name: 'Uzbekistán' },
    { code: 'VCT',	 name: 'San Vicente y las Granadinas' },
    { code: 'VEN',	 name: 'Venezuela' },
    { code: 'VGB',	 name: 'Islas Vírgenes Británicas' },
    { code: 'VIR',	 name: 'Islas Vírgenes (EE.UU.)' },
    { code: 'VNM',	 name: 'Viet Nam' },
    { code: 'VUT',	 name: 'Vanuatu' },
    { code: 'WLD',	 name: 'Mundo' },
    { code: 'WSM',	 name: 'Samoa' },
    { code: 'XKX',	 name: 'Kosovo' },
    { code: 'YEM',	 name: 'Yemen, Rep. del' },
    { code: 'ZAF',	 name: 'Sudáfrica' },
    { code: 'ZMB',	 name: 'Zambia' },
    { code: 'ZWE',	 name: 'Zimbabwe' }
];